# Generated by Django 3.0.8 on 2020-07-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
